language: csharp
os: linux
dist: trusty
sudo: false
dotnet: 2.0.3
mono: none

addons:
  apt:
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.5
    - dotnet-runtime-2.0.0

script:
  - dotnet --info
  - dotnet new console --name test && cd test
  - sed -i "s/netcoreapp2.0/netcoreapp1.1.5/g" test.csproj
  - cat test.csproj
  - dotnet run
