language: c
sudo: true
dist: trusty

os: linux

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 417A0893
  - sudo apt-get update -qq
  - sudo apt-get install -qq dotnet-dev-1.0.0-preview2-003121



