language: csharp
solution: travis-mono-test.sln
sudo: false
os:
  - osx
mono:
  - 4.4.1
matrix:
  exclude:
    - os: osx
      mono: 2.10.8
script:
  - eval $(/usr/libexec/path_helper -s)
  - xbuild /p:Configuration=Release travis-mono-test.sln
  - mono travis-mono-test/bin/Release/travis-mono-test.exe


