language: csharp

matrix:
  include:
    - os: osx
      osx_image: xcode9
      dotnet: 2.0.3
      mono: none
      env: DOTNETCORE=1
    - os: osx
      osx_image: xcode9
      dotnet: 1.1.5
      mono: none
      env: DOTNETCORE=1
    - os: linux
      dist: xenial
      sudo: false
      dotnet: 2.1
      mono: none
      env: DOTNETCORE=1
    - os: linux
      dist: xenial
      sudo: false
      dotnet: 2.0.3
      mono: none
      env: DOTNETCORE=1
    - os: linux
      dist: xenial
      sudo: required
      dotnet: 2.0.3
      mono: none
      env: DOTNETCORE=1
    - os: linux
      dist: xenial
      dotnet: 1.1.5
      mono: none
      env: DOTNETCORE=1
    - os: linux
      mono: latest
      dist: precise
      sudo: false
    - os: linux
      mono: nightly
      dist: xenial
    - os: linux
      mono: latest
      dist: xenial
      sudo: false
    - os: linux
      mono: alpha
      dist: xenial
      sudo: false
    - os: linux
      mono: beta
      dist: xenial
      sudo: false
    - os: linux
      mono: weekly
      dist: xenial
      sudo: false
    - os: linux
      mono: 5.2.0
      sudo: false
    - os: linux
      mono: 4.6.2
      sudo: false
    - os: linux
      mono: 4.4.1
      sudo: false
    - os: linux
      mono: 4.4.0
      sudo: false
    - os: linux
      mono: 4.2.4
      sudo: false
    - os: linux
      mono: 4.0.5
      sudo: false
    - os: linux
      mono: 3.12.0
      sudo: false
    - os: linux
      mono: 3.10.0
      sudo: false
    - os: linux
      mono: 3.8.0
      sudo: false
    - os: osx
      mono: alpha
    - os: osx
      mono: beta
    - os: osx
      mono: weekly
    - os: osx
      mono: latest
    - os: osx
      mono: 5.2.0
    - os: osx
      mono: 4.4.1
    - os: osx
      mono: 4.4.0
    - os: osx
      mono: 4.2.4
    - os: osx
      mono: 4.0.5
    - os: osx
      osx_image: xcode6.4
      mono: 3.12.0
    - os: osx
      osx_image: xcode6.4
      mono: 3.10.0

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - cat $HOME/build.sh
  - echo $STANDARD_CI_SOURCE_REVISION_ID $STANDARD_CI_REPOSITORY_URL $STANDARD_CI_REPOSITORY_TYPE
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 1024; fi

script:
  - if [ -z $(which msbuild) ]; then export MSBUILD=xbuild; else export MSBUILD=msbuild; fi
  - if [ -n "${DOTNETCORE}" ]; then mkdir bla && cd bla && dotnet new console && time dotnet restore && dotnet run; fi
  - if [ -z "${DOTNETCORE}" ]; then $MSBUILD /p:Configuration=Release travis-mono-test.sln; fi
  - if [ -z "${DOTNETCORE}" ]; then mono travis-mono-test/bin/Release/travis-mono-test.exe; fi

