language: csharp
solution: travis-mono-test.sln

mono: none
dotnet: 1.0.0-preview2-003121
sudo: true
dist: trusty

cache:
  directories:
    - $HOME/.nuget

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - mkdir bla && cd bla
  - dotnet new
  - time dotnet restore
  - dotnet run



