language: csharp
solution: travis-mono-test.sln

matrix:
  include:
    - os: linux
      mono: latest
      sudo: false
    - os: linux
      mono: alpha
      sudo: false

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - env
  - ls -la $HOME
  - ls -la $HOME/.config || true

install:
  - env
  - ls -la $HOME
  - ls -la $HOME/.config || true
  - nuget restore
  - ls -la $HOME
  - ls -la $HOME/.config || true

script:
  - if [ -n "${DOTNETCORE}" ]; then mkdir bla && cd bla && dotnet new && time dotnet restore && dotnet run; fi
  - if [ -z "${DOTNETCORE}" ]; then xbuild /p:Configuration=Release travis-mono-test.sln; fi
  - if [ -z "${DOTNETCORE}" ]; then mono travis-mono-test/bin/Release/travis-mono-test.exe; fi
