language: csharp
solution: travis-mono-test.sln

mono: none
dotnet: dotnet-dev-1.0.0-preview2-003121

dist: trusty
sudo: true
xcode_image: xcode7.3

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/.nuget

notifications:
  email:
    on_success: change
    on_failure: always
    
script:
  - mkdir bla && cd bla
  - dotnet new
  - time dotnet restore
  - dotnet run
