language: csharp
solution: travis-mono-test.sln

mono: none
dotnet: 1.0.0-preview2-003121
sudo: true
dist: trusty
osx_image: xcode7.3

os: linux

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - sudo apt-get update -qq
  - sudo apt-get upgrade -qq
  - mkdir bla && cd bla
  - dotnet new
  - time dotnet restore
  - dotnet run
  - cd ..
  - xbuild /p:Configuration=Release travis-mono-test.sln
  - mono travis-mono-test/bin/Release/travis-mono-test.exe



