language: csharp
solution: travis-mono-test.sln
sudo: false
mono:
  - latest
  - 3.12.0
  - 3.10.0
  - 3.8.0
  - 2.10.8
script:
  - xbuild /p:Configuration=Release travis-mono-test.sln
  - mono travis-mono-test/bin/Release/travis-mono-test.exe
