language: csharp
solution: travis-mono-test.sln
sudo: true
dist: trusty

mono: none
dotnet: dotnet-dev-1.0.0-preview2-003121

notifications:
  email:
    on_success: change
    on_failure: always
script:
  - dotnet new
  - dotnet restore
  - dotnet run
