language: csharp
solution: travis-mono-test.sln

matrix:
  include:
    - sudo: true
      dist: trusty
      dotnet: dotnet-dev-1.0.0-preview2-003121
    - mono: latest
      sudo: false

cache:
  directories:
    - $HOME/.nuget

notifications:
  email:
    on_success: change
    on_failure: always
    
script:
  - mkdir bla && cd bla
  - dotnet new
  - time dotnet restore
  - dotnet run
