language: csharp
solution: travis-mono-test.sln

mono: 4.2.4
dotnet: none
sudo: true
dist: trusty
osx_image: xcode7.3

os:
  - osx
  - linux

cache:
  directories:
    - $HOME/.nuget

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - mkdir bla && cd bla
  - dotnet new
  - time dotnet restore
  - dotnet run



