language: csharp
solution: travis-mono-test.sln
sudo: false
os:
  - osx
mono:
  - 4.4.1
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - xbuild /p:Configuration=Release travis-mono-test.sln
  - mono travis-mono-test/bin/Release/travis-mono-test.exe
