language: csharp
solution: travis-mono-test.sln

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      dotnet: 1.0.0-preview2-003121
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
    - os: linux
      mono: alpha
      sudo: false

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - mkdir bla && cd bla
  - dotnet new
  - time dotnet restore
  - dotnet run
  - cd ..
  - xbuild /p:Configuration=Release travis-mono-test.sln
  - mono travis-mono-test/bin/Release/travis-mono-test.exe


