language: csharp
solution: travis-mono-test.sln
sudo: false
os:
  - linux
mono:
  - latest
matrix:
  exclude:
    - os: osx
      mono: 2.10.8
script:
  - xbuild /p:Configuration=Release travis-mono-test.sln
  - mono travis-mono-test/bin/Release/travis-mono-test.exe
