language: csharp
solution: travis-mono-test.sln
services: docker
os: linux
mono: latest
script:
  - xbuild /p:Configuration=Release travis-mono-test.sln
  - mono travis-mono-test/bin/Release/travis-mono-test.exe
