language: csharp
solution: travis-mono-test.sln

mono: latest
dotnet: none

cache:
  directories:
    - $HOME/.nuget

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - mkdir bla && cd bla
  - dotnet new
  - time dotnet restore
  - dotnet run




